<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo128.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2 style="color: #228B22; text-align: center;">Cadastro realizado com sucesso :)</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="/" class="btn btn-success btn-block" style=" border-radius: 50px;">Clique aqui para fazer login</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  