<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo64.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">

            <?php if($this->view->erroCadastro == true) {?>

                <div class="bg bg-danger text-white text-center p-2 " style="border-radius: 50px;">Dados invalidos ou usuário com este e-mail já existe</div>
                <br/>

            <?php } ?>
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Nome" name="nome" 
                value="<?php echo $this->view->usuario['nome'] ?>">
              </div>
              
              <div class="form-group">
                <input type="text" class="form-control" placeholder="E-mail" name="email"
                value="<?php echo $this->view->usuario['email'] ?>">
              </div>

              <div class="form-group">
                <input type="password" class="form-control" placeholder="Senha" name="senha"
                value="<?php echo $this->view->usuario['senha'] ?>">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail, nome ou número de telefone fornecido.
                </small>
              </div>
              <button type="submit" class="btn btn-success btn-block" style="border-radius: 50px;">Inscrever-se</button>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  