

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"> <?php echo $_SESSION['nome'] ?> </span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_tweets['total_tweet'] ?> </span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguindo['total_seguindo'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguidores['total_seguidores'] ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-warning">Tweetar</button>
						</div>

					</form>
				</div>
			</div>


			<?php foreach ($this->view->tweets as $id_tweet => $tweet) { ?>
			
				
			<div class="row tweet">

				<div class="col">
					<p><strong><?= $tweet['nome']?></strong> 
						<small><span class="text text-muted">- <?= $tweet['data']?></span></small>
					</p>
					<p><?= $tweet['tweet']?></p>

					

					<br />

					<?php if($tweet['id_usuario'] == $_SESSION['id']) { ?>
						
					<form  method="get" action="/delete_tweet">
						<div class="col d-flex justify-content-end">
							<input type="hidden" name="deletetweet" value="<?= $tweet['id'] ?>" >
							<button  type="submit" class="btn btn-danger"><small>Remover</small></button>
							
						</div>
					</form>

					<?php } ?>
				</div>
			</div>

		
		<?php } ?>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr style="color:#228B22" />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>