<html>
	<head>
		<meta charset="utf-8" />
		<title>AmazonTweet</title>

		 <link rel="icon" href="img/favicon.png">

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<link rel="stylesheet" type="text/css" href="/css/style.css">


	</head>

	<body>

		<div class="navbar" style="background-color: #228B22; height: 75px;">
			<div class="navbar-brand">
				
					<img src="img/twitter_logo32.png">
					<strong class="navbar-text text-white">AmazonTweet</strong>
			 	
			</div>

			<nav class="navbar navbar-expand-lg menu">
	<div class="container">

		<?php 

		if( isset($_SESSION['id'])  && isset($_SESSION['nome']) ){ ?>

			

	  <div class="navbar-nav menubotoes d-inline" >

	  	<a class="menuItem"  href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem " href="/sair">
	  		Sair
	  	</a>
			
	  </div>

	<?php }else{

	} ?>
	

	
	</div>
</nav>

		</div>


		<?= $this->content() ?>
	</body>

</html>